### ISSUE TITLE
failure to login: NullPointerException: invalid null input: name

### ISSUE THREAD

**Issue by abroskin** [exasol/cloud-storage-etl-udfs#75]
Hi,
I try to use this UDF to ingest Parquet formats and keep receiving the following error:

`[2020-03-03 14:03:39] [22002] VM error:
[2020-03-03 14:03:39] org.apache.hadoop.security.KerberosAuthException: failure to login: javax.security.auth.login.LoginException: java.lang.NullPointerException: invalid null input: name
[2020-03-03 14:03:39] 	at com.sun.security.auth.UnixPrincipal.<init>(UnixPrincipal.java:71)
[2020-03-03 14:03:39] 	at com.sun.security.auth.module.UnixLoginModule.login(UnixLoginModule.java:133)
[2020-03-03 14:03:39] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-03 14:03:39] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-03 14:03:39] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-03 14:03:39] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2020-03-03 14:03:39] 	at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
[2020-03-03 14:03:39] 	at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
[2020-03-03 14:03:39] 	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
[2020-03-03 14:03:39] 	at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
[2020-03-03 14:03:39] 	at java.security.AccessController.doPrivileged(Native Method)
[2020-03-03 14:03:39] 	at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
[2020-03-03 14:03:39] 	at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
[2020-03-03 14:03:39] 	at org.apache.hadoop.security.UserGroupInformation$HadoopLoginContext.login(UserGroupInformation.java:1926)
[2020-03-03 14:03:39] 	at org.apache.hadoop.security.UserGroupInformation.doSubjectLogin(UserGroupInformation.java:1837)
[2020-03-03 14:03:39] 	at org.apache.hadoop.security.UserGroupInformation.createLoginUser(UserGroupInformation.java:710)
[2020-03-03 14:03:39] 	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:660)
[2020-03-03 14:03:39] 	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:571)
[2020-03-03 14:03:39] 	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3487)
[2020-03-03 14:03:39] 	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3477)
[2020-03-03 14:03:39] 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3319)
[2020-03-03 14:03:39] 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
[2020-03-03 14:03:39] 	at com.exasol.cloudetl.bucket.Bucket.fileSystem$lzycompute(Bucket.scala:60)
[2020-03-03 14:03:39] 	at com.exasol.cloudetl.bucket.Bucket.fileSystem(Bucket.scala:59)
[2020-03-03 14:03:39] 	at com.exasol.cloudetl.bucket.Bucket.getPaths(Bucket.scala:68)
[2020-03-03 14:03:39] 	at com.exasol.cloudetl.scriptclasses.ImportMetadata$.run(ImportMetadata.scala:22)
[2020-03-03 14:03:39] 	at com.exasol.cloudetl.scriptclasses.ImportMetadata.run(ImportMetadata.scala)
[2020-03-03 14:03:39] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2020-03-03 14:03:39] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2020-03-03 14:03:39] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2020-03-03 14:03:39] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2020-03-03 14:03:39] 	at com.exasol.ExaWrapper.run(ExaWrapper.java:186)
[2020-03-03 14:03:39] Stack trace:
[2020-03-03 14:03:39] org.apache.hadoop.security.UserGroupInformation.doSubjectLogin(UserGroupInformation.java:1847)
[2020-03-03 14:03:39] org.apache.hadoop.security.UserGroupInformation.createLoginUser(UserGroupInformation.java:710)
[2020-03-03 14:03:39] org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:660)
[2020-03-03 14:03:39] org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:571)
[2020-03-03 14:03:39] org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3487)
[2020-03-03 14:03:39] org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3477)
[2020-03-03 14:03:39] org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3319)
[2020-03-03 14:03:39] org.apache.hadoop.fs.FileSystem.get(FileSystem.java:479)
[2020-03-03 14:03:39] com.exasol.cloudetl.bucket.Bucket.fileSystem$lzycompute(Bucket.scala:60)
[2020-03-03 14:03:39] com.exasol.cloudetl.bucket.Bucket.fileSystem(Bucket.scala:59)
[2020-03-03 14:03:39] com.exasol.cloudetl.bucket.Bucket.getPaths(Bucket.scala:68)
[2020-03-03 14:03:39] com.exasol.cloudetl.scriptclasses.ImportMetadata$.run(ImportMetadata.scala:22)
[2020-03-03 14:03:39] com.exasol.cloudetl.scriptclasses.ImportMetadata.run(ImportMetadata.scala)
[2020-03-03 14:03:39] (Session: 1660147398588182131)` 

The error is the same wether I load from GCS or S3.

Exasol node runs on kubernetes:
image: exasol/docker-db:6.1.6-d1
udf function: cloud-storage-etl-udfs-0.6.1.jar

Thanks,
Alex

**Comment by morazow** [comment]
Hello @abroskin,

Is the Exasol installation based on the docker? If so, could you please try using the following [jar file](https://drive.exasol.com/f/bcb9592341dc42debd26/)?

**Comment by abroskin** [comment]
> Hello @abroskin,
> 
> Is the Exasol installation based on the docker? If so, could you please try using the following [jar file](https://drive.exasol.com/f/bcb9592341dc42debd26/)?

Hi @morazow ,
Thanks for the quick reply.
Yes your jar works perfectly.
Is there a public link to this build?

Thanks

**Comment by morazow** [comment]
Hey @abroskin ,
Yes, some of the forks of the project maintain the version for the docker installations.
- https://github.com/mymindwentblvnk/cloud-storage-etl-udfs/releases

The jar I have send you is the manual compilation of same fix. In the long run, we plan to also release the versions for docker here with separate branch. You can see the small changes needed [here](https://github.com/exasol/cloud-storage-etl-udfs/pull/59/files).
